name:                cygnet
version:             0.1.0.0
github:              "keharriso/cygnet"
license:             MIT
author:              "Kevin Harrison"
maintainer:          "keharriso@gmail.com"
copyright:           "2023 Kevin Harrison"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/keharriso/cygnet#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6 && < 0.7
- parsec >= 3.1 && < 3.2
- indents >= 0.5 && < 0.6
- transformers >= 0.5 && < 0.6
- text >= 1.2 && < 1.3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - ocelot

executables:
  cygnet-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cygnet
    - ocelot

tests:
  cygnet-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cygnet
